services:

  app:
    build: .  
    container_name: idcard-app
    ports:
      - "8443:8080"
      - "2222:22"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/GA-loengpheaktra-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hello@123

  db:
    image: mysql:8.0
    container_name: idcard-mysql
    restart: always
    environment:
      MYSQL_DATABASE: GA-loengpheaktra-db
      MYSQL_ROOT_PASSWORD: Hello@123
    ports:
      - "3307:3306"